"""Add tables blockchain, transaction_in_block 

Revision ID: 884fc16090c7
Revises: 
Create Date: 2023-05-09 04:52:42.269086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884fc16090c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('admin_sign', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_block_id'), 'block', ['id'], unique=False)
    op.create_table('transaction_in_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_in_block_id'), 'transaction_in_block', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_in_block_id'), table_name='transaction_in_block')
    op.drop_table('transaction_in_block')
    op.drop_index(op.f('ix_block_id'), table_name='block')
    op.drop_table('block')
    # ### end Alembic commands ###
